name: mailbox
description: Messenger MailBox

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_bloc: ^6.1.1
  shared_preferences: ^0.5.12+4
  connectivity: ^2.0.2

  #firebase_core: ^0.5.0
  #cloud_firestore: ^0.16.0
  #firebase_auth: ^0.20.0+1

  #firebase_core: ^0.7.0
  #firebase_core: ^0.4.0+6
  #firebase_database: ^3.0.3
  #firebase_auth: ^0.11.1+7
  #firebase_storage: ^3.0.2

  firebase_core: ^0.7.0
  #firebase_crashlytics: ^0.4.0+1
  #firebase_analytics: ^7.0.1
  firebase_auth: ^0.20.0+1
  firebase_storage: ^7.0.0
  firebase_database: ^6.0.0
  #cloud_firestore: ^0.16.0




  intl: ^0.16.1

  #firebase_analytics: ^5.0.2
  #firebase_dynamic_links: ^0.5.1
  page_transition: ^1.1.7+6
  animated_button: ^0.1.3
  animated_icon_button: ^0.3.0
  #firebase_database: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    -  assets/icons/
